### ISSUE TITLE
Feature request: adding files without a prefix in the ZIP archive

### ISSUE THREAD

**Issue by gwerbin** [dairiki/hatch-zipped-directory#1]
Thanks for the useful Hatch plugin!

It would be very useful if we could pass a null "root path" for the ZIP archive, thereby *disabling* the filename prefix for archive members.

That is, if I have the following project:

```
src/
  a.py
  b.py
  c.py
```

would like to be able to write `install-name = ''` and `sources = [ 'src' ]` and obtain the following archive members:

```
a.py
b.py
c.py
MANIFEST.json
```

Currently this can be achieved by setting `install-name = '.'` in the plugin config, but this seems somewhat dependent on undocumented behaviors of the `ZipFile` class and the `unzip` utility.

Here is my (not-yet-tested) patch to implement explicit support for `install-name = ''`: https://github.com/dairiki/hatch-zipped-directory/compare/master...gwerbin:hatch-zipped-directory:support-null-install-name

If you're interested, I can try working this into the test suite, although it might be a little tricky given the current fixture setup. Also happy to consider alternative designs.

**Comment by dairiki** [comment]
@gwerbin Thank you for the suggestion and patch!

I've implemented this [in this commit](7009d3f19c32385d19ccd3d0d0e16536cb855f58), more or less following your patch.  I've just published release 0.1.0b2 which includes this.

**Comment by gwerbin** [comment]
Nice, this is going to be really useful for me!
